### ISSUE TITLE
Breakpoints messages sent multiple times

### ISSUE THREAD

**Issue by JohanMabille** [jupyterlab/debugger#101] opened 2019-10-27 14:45 UTC
As described in #89:

![multiple-messages-breakpoints](https://user-images.githubusercontent.com/591645/67632532-cbdb9080-f8a4-11e9-910f-64e6abf454b8.gif)

It looks like the handlers are not removed correctly when switching between notebooks and cells.

**Comment by jtpio** [comment] 2019-11-12 11:33
This seems to be fixed on master now (couldn't reproduce locally).

**Comment by jtpio** [comment] 2019-11-14 14:32
I haven't been able to reproduce it on master.

Some recent PRs have helped fixing that, so let's consider it as fixed for now.

**Closed by jtpio** 2019-11-14 14:32 UTC
