### ISSUE TITLE
Debugger on/off button not available for kernels on conda-envs

### ISSUE THREAD

**Issue by etiecher** [jupyterlab/debugger#475] opened 2020-06-17 18:46 UTC
Dear all,

I'm having some difficulties trying to set-up the debugger on an environment.

I've created a conda environment 'jupyterlab_2' in order to use the extension. I've installed the xpython kernel, the debugger extension and all depencies (eg.: nodejs) only on this environment.

After that, Jupyter gives me some options to use as kernels for my notebooks. Specifically for xpython, there are two: (1) a 'clean' xpython kernel; (2) a second one associated with the above environment.

The debugger on/off button on the notebook window appears only when the first kernel (xpython) is choosen. Below there are two screenshots, one for each kernel:
![xpython](https://user-images.githubusercontent.com/11812843/84937014-84af4380-b0b1-11ea-9b4c-db3924eafa42.png)
![xpython_with_conda_env](https://user-images.githubusercontent.com/11812843/84937023-85e07080-b0b1-11ea-9bef-96d01b425e14.png)

 Any ideas on what am I missing?
Additionally, none of conda shell commands work (eg.: !conda info)

 Thanks in advance.

**Comment by jtpio** [comment] 2020-06-18 07:20
@etiecher which version of the extension and `xeus-python` is it?

The latest `0.3.0-beta.1` requires `xeus-python=0.8.0`.

**Comment by etiecher** [comment] 2020-06-18 14:28
xeus-python=0.8.0
@jupyterlab/debugger= v0.3.0-beta.1

**Comment by jtpio** [comment] 2020-06-18 16:52
Thanks @etiecher for the details, the versions look good.

Normally this should fine if Jupyter is started from your `jupyterlab_2` environment?

**Comment by etiecher** [comment] 2020-06-18 18:48
I`m using conda CLI. First I'm activating the env 'jupyterlab_2' and then running 'jupyter lab'. However, you gave me the idea to look at jupyter config file. I couldn't find a config file specific for each env. There is only one file on ./.jupyter folder. It has a default kernel (python3). I set the option 
c.MultiKernelManager.default_kernel_name = 'xpython', but it still opens with python3 (than I can change, but the problem is still there).
I also though about setting the kernel type of the env, but it seems that it must be done when creating it. I created it as simple as possible (conda env create --name jupyterlab_2).
I also have an extension to manage conda envs on jupyterlab. Perhaps it is the problem. I tried to disable it, but nothing changed.
Another possible solution. On the xeus-python page is recommended to install a specific 'xeus-python jupyterlab'. Never heard of that. But I would have to set-up everything again.
So, three possibilities. @jtpio , any thoughts on with path is more likely to solve the issue? I`m prone to the third option.

**Comment by jtpio** [comment] 2020-06-18 20:30
> I also have an extension to manage conda envs on jupyterlab.

It sounds like this could indeed be the problem. Which extension is it?

There is one notable change with the latest releases (xpython `0.8.0` and the debugger extension `0.3.0-beta.1`). The extension uses the kernel specs to check whether it contains the `debugger` key. If it does, it adds the button to the notebook toolbar. Otherwise it doesn't add the button.

Another thing to try would be to list the kernel specs from the `jupyterlab_2` environment with:

```
jupyter kernelspec list
```

Which should outputs something like this:

```
  python3    /path/to/miniconda/envs/jupyterlab_2/share/jupyter/kernels/python3
  xpython    /path/to/miniconda/envs/jupyterlab_2/share/jupyter/kernels/xpython
``

Then check the content of the `kernel.json` file in the xpython folders.

> On the xeus-python page is recommended to install a specific 'xeus-python jupyterlab'

This is for installing `xeus-python` and `jupyterlab` in one go with the same command. So it should be fine :+1:

**Comment by etiecher** [comment] 2020-06-19 00:12
> It sounds like this could indeed be the problem. Which extension is it?
> 
jupyterlab_conda v2.1.2
I wasn't using different kernels before this big change on my IDE and I was doing env mgmt only on CLI. Anyway, that was exactly the source of the problem. More specifically, the package jupyter_conda, not the extensions (jupyterlab_toastify, jupyterlab_conda).
Unfortunatelly, it is not possible to uninstall (it uninstalls other importante packages).

> There is one notable change with the latest releases (xpython `0.8.0` and the debugger extension `0.3.0-beta.1`). The extension uses the kernel specs to check whether it contains the `debugger` key. If it does, it adds the button to the notebook toolbar. Otherwise it doesn't add the button.
>
The kernel itself it's right, but jupyter_conda presents it in the window as a concat of the kernel name with env name. Perhaps doing the check through a different source I might solve the issue.
Can you give some directions where can I find it in the files of the package? I'm not experienced with extensions nor java. Otherwise, do you think a previous version would avoid that?
 
> This is for installing `xeus-python` and `jupyterlab` in one go with the same command. So it should be fine 👍

Yeah, I felt really bad for myselft on that one..

**Comment by jtpio** [comment] 2020-06-19 08:57
Thanks a lot @etiecher for these details.

It looks like it is an issue with `jupyterlab_conda`, or more precisely with the `nb_conda_kernels` package, which overrides the existing kernel spec metadata.

As a consequence the debugger extension is not able to determine whether the kernel supports debugging, and doesn't show the button in the notebook toolbar.

I have opened an issue on the repo here: https://github.com/fcollonval/jupyter_conda/issues/45

**Comment by jtpio** [comment] 2020-06-19 09:04
For reference, this is reproducible on the `jupyterlab_conda` Binder: https://mybinder.org/v2/gh/fcollonval/jupyter_conda/master?urlpath=lab

By opening the Conda Packages Manager and installing `xeus-python`.

**Comment by etiecher** [comment] 2020-06-19 13:39
Thanks @jtpio  Glad to help. 
So, this is my first contribution/open-issue on github.
Should I close this thread?
Any advice on how to follow-up on the opened issues with juyter_conda#45 or nb_conda_kernels#160?

**Comment by jtpio** [comment] 2020-06-19 13:53
Thanks @etiecher, and congrats on your first contribution!

https://github.com/Anaconda-Platform/nb_conda_kernels/issues/160 is the one to follow.

The idea would be to wait for a maintainer of `nb_conda_kernels` to submit a fix and then release a new version.

Alternatively you could also try to open a PR if you want? The fix probably requires merging the `metadata` dictionary here: https://github.com/Anaconda-Platform/nb_conda_kernels/blob/1b9e821e7cafe388b633ba4fdb8feb3eec815d6c/nb_conda_kernels/manager.py#L196-L199 

We can leave this issue open for now for visibility.

**Comment by jtpio** [comment] 2020-07-09 09:51
@etiecher it looks like there is now a new release of `nb_conda_kernels` which includes the fix.

Were you able to give it another try to see if it addresses the issue?

**Comment by etiecher** [comment] 2020-07-09 15:28
Hi jtpio,
After your message, I looked at the channels (conda-forge and pkgs/main) and the last version is still the same that I have (2.2.3). Only change was in the build (from py37_0 to py38_0). It seems to me that nothing has changed or at least it wasn't published yet.
Also, I didn't install nb_conda_kernels (I believe it was a dependence of jupyter_conda). This package didn't have any changes at all in the same channels.
I know I can get the packages straight from github, but I'm not confident yet to manage envs that way. I'm afraid of messing up with something that is working fine right now. I'll wait some time to see if the channels are updated, than try to create a new env from scracth and see if it works.

Just to be sure, I went to the same place you told me to solve the issue before (in fact, I changed my code locally and its working). It looks like they updated exactly that part of the code:
PREVIOUS:
`               spec['metadata'] = {
                    'conda_env_name': env_name,
                    'conda_env_path': env_path
                }
 `
 LATEST:
`metadata = spec.get('metadata', {})`
`              metadata.update({
                    'conda_env_name': env_name,
                    'conda_env_path': env_path
                })
`
 `               spec['metadata'] = metadata
`

**Comment by jtpio** [comment] 2020-07-09 15:59
Ah ok, according to the Releases page it looks like 2.2.4 was tagged a few hours ago: 

https://github.com/Anaconda-Platform/nb_conda_kernels/releases

But it might indeed no be available on conda yet.

**Comment by jtpio** [comment] 2020-09-29 11:32
@etiecher 

Just tried on the `jupyter_conda` Binder (https://github.com/mamba-org/jupyter_conda) which uses `nb_conda_kernels` 2.2.4.

After installing `xeus-python` and `@jupyterlab/debugger`, it looks like the debugger can be used normally:

![nb-conda-kernels](https://user-images.githubusercontent.com/591645/94553036-266d3180-0258-11eb-9438-96a1097f11f6.gif)

Closing as fixed, let me know if you have any other issue.

**Closed by jtpio** 2020-09-29 11:32 UTC

**Comment by etiecher** [comment] 2020-09-30 15:17
Great! I didn't test yet as I said, but thanks for your help!
