### ISSUE TITLE
AttributeError: module 'sys' has no attribute 'argv'

### ISSUE THREAD

**Issue by yulius-fxpal** [jupyterlab/debugger#319] opened 2019-12-21 03:50 UTC
Crash when enabling debugger.  I don't know why sys has no argv set.  This only happens to some users and not others.

I made a work around patch by putting the error in a try/catch.

```
    def _send_process_event(self, py_db, start_method):
        try:
            if len(sys.argv) > 0:
                name = sys.argv[0]
            else:
                name = ''
        except:
            name = ''
```

Crash stack trace:

```
Traceback (most recent call last):
  File "/home/user/.conda/envs/tensorflow1_15/lib/python3.6/site-packages/ptvsd/_vendored/pydevd/_pydevd_bundle/pydevd_comm.py", line 283, in _on_run
    self.process_net_command_json(self.global_debugger_holder.global_dbg, json_contents)
  File "/home/user/.conda/envs/tensorflow1_15/lib/python3.6/site-packages/ptvsd/_vendored/pydevd/_pydevd_bundle/pydevd_process_net_command_json.py", line 164, in process_net_command_json
    cmd = on_request(py_db, request)
  File "/home/user/.conda/envs/tensorflow1_15/lib/python3.6/site-packages/ptvsd/_vendored/pydevd/_pydevd_bundle/pydevd_process_net_command_json.py", line 314, in on_attach_request
    return self._handle_launch_or_attach_request(py_db, request, start_reason='attach')
  File "/home/user/.conda/envs/tensorflow1_15/lib/python3.6/site-packages/ptvsd/_vendored/pydevd/_pydevd_bundle/pydevd_process_net_command_json.py", line 297, in _handle_launch_or_attach_request
    self._send_process_event(py_db, start_reason)
  File "/home/user/.conda/envs/tensorflow1_15/lib/python3.6/site-packages/ptvsd/_vendored/pydevd/_pydevd_bundle/pydevd_process_net_command_json.py", line 278, in _send_process_event
    if len(sys.argv) > 0:
AttributeError: module 'sys' has no attribute 'argv'
```

**Comment by jtpio** [comment] 2019-12-21 12:25
Thanks @yulius-fxpal for opening this issue.

Does this happen only when enabling the debugger, or also when running the code?

Do you have some sample code to share that could help reproducing the issue? And which version of `ptvsd` is installed? (`conda list | grep ptvsd`)

**Comment by yulius-fxpal** [comment] 2019-12-21 19:49
> Does this happen only when enabling the debugger, or also when running the code?

This happens when clicking on the toggle button to enable the debugger.  When running the code without the debugger, everything works fine.

> Do you have some sample code to share that could help reproducing the issue?

1. Created a new conda envrionment w/ `conda install -c conda-forge xeus-python ptvsd`
2. Create new notebook w/ new conda environment
3. Create cell similar to the example gif
```
def add(a,b):
    return a+b
x = add(3,4)
print(x)
```
4. Click on the debug toggle button and the error pops up

> And which version of ptvsd is installed? (conda list | grep ptvsd)

```
$ conda list | grep ptvsd
ptvsd                     4.3.2            py36h516909a_0    conda-forge
```

**Comment by jtpio** [comment] 2019-12-23 09:40
Thanks @yulius-fxpal for the details.

I tried in a fresh new conda environment with Python 3.6 and it indeed seems to be an issue:

```bash
conda create -n debugger -c conda-forge python=3.6 ptvsd xeus-python jupyterlab
conda activate debugger
jupyter labextension install @jupyterlab/debugger
```

However using Python 3.7 seems to be fine. Would you mind trying with Python 3.7 just to double check?

**Comment by yulius-fxpal** [comment] 2020-01-02 17:35
Happy new year @jtpio !  Yes it would appear upgrading to 3.7 solves this issue.

```
conda install python=3.7
```

**Comment by jtpio** [comment] 2020-01-06 18:33
Thanks @yulius-fxpal for checking!

This still looks like an issue to me, and we would need to check more in details why Python 3.6 behaves differently. 

The problem is most likely coming from `xeus-python`, so maybe we can create a small code snippet to reproduce the error first (without installing the `@jupyterlab/debugger` extension), and then open an issue there? https://github.com/jupyter-xeus/xeus-python

**Comment by jtpio** [comment] 2020-09-29 11:39
Closing, as this appears to be related to the `xeus-python` kernel and not the debugger extension.

@yulius-fxpal feel free to open a new issue in https://github.com/jupyter-xeus/xeus-python if you are still experiencing the error.

**Closed by jtpio** 2020-09-29 11:39 UTC
Labels: bug
