### ISSUE TITLE
Continue or next after break point on a last line of a call

### ISSUE THREAD

**Issue by ChaosPredictor** [jupyterlab/debugger#559] opened 2020-10-22 18:53 UTC
After pressing continue/next on the last line of a call the debugger stucks, it likes don't want to move to next cell.

[video](https://youtu.be/R22tDE6roWQ) that showing it

**Comment by jtpio** [comment] 2020-10-23 09:01
Thanks @ChaosPredictor.

This is expected behavior since the debugger follows the pattern used by the notebook when executing code.

But it is possible to queue the next cell for execution by clicking on the next cell and running it:

![queue-cell-execution](https://user-images.githubusercontent.com/591645/96978604-d283fe80-151e-11eb-9a11-baad8438b8e7.gif)

**Comment by jtpio** [comment] 2021-01-04 13:22
Closing as answered.

@ChaosPredictor feel free to open a new issue in https://github.com/jupyterlab/jupyterlab if you have more questions about the design and UX of the debugger. Thanks!

**Closed by jtpio** 2021-01-04 13:22 UTC
